// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FAJ6eJ_LpZZS_6Hjf37s1ZAas36Zf6U',
    appId: '1:334772772833:android:9b97adcac51d1e559f7ca0',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'bookmeri-20ae4',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'bookmeri-20ae4.appspot.com',
  );
  // FirebaseOptions androidOptions = FirebaseOptions.Builder()
  //     .setApiKey("AIzaSyD6pd46r6N3QbxFFLQC94x1cVZq595x9xw")
  //     .setApplicationId("1:334772772833:android:9b97adcac51d1e559f7ca0")
  //     .setProjectId("bookmeri-20ae4")
  //     .build();

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FAJ6eJ_LpZZS_6Hjf37s1ZAas36Zf6U',
    appId: '1:334772772833:ios:5818815613a9a8d09f7ca0',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'bookmeri-20ae4',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'bookmeri-20ae4.appspot.com',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: '334772772833-bqq7c3c5j6isir4eqmefb2r1bmil7cih.apps.googleusercontent.com',
    iosBundleId: 'com.nextlevel.bookmeri',
  );

}